name: tapsalon
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"
module:
  androidX: true


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.5+1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6
  intl: ^0.16.1
  google_maps_flutter: ^0.5.21+15
  geolocator: ^5.2.0
  font_awesome_flutter: ^8.5.0
  percent_indicator: ^2.1.1+1
  smooth_star_rating: ^1.0.4+2
  flutter_spinkit: ^4.1.1
  flutter_widget_from_html_core: ^0.3.2+1
  share: ^0.6.3+5
  image_picker: ^0.6.2+3
  url_launcher: ^5.4.1
  search_widget: ^1.0.2
  flutter_svg: ^0.17.1
  shamsi_date: ^0.8.1
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
#  najvaflutter: ^1.2.3
#  flutter_secure_storage: ^3.3.3

  #  table_calendar: ^2.2.1
#  syncfusion_flutter_calendar: ^17.4.50-beta
#  splashscreen: ^1.2.0
#  jalali_calendar: ^0.1.5
#  oauth1: ^1.0.4

#  sqflite: ^1.1.7+3
#  rxdart: ^0.22.6
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/images/tapsalon_icon_200.png
    - assets/images/userImage.png
    - assets/images/volleyball_player.png
    - assets/images/gym.png
    - assets/images/salon.png
    - assets/images/swimming.png
    - assets/images/marker1.png

  fonts:

    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobile_Bold.ttf
        - asset: assets/fonts/IRANSansMobile_Light.ttf
        - asset: assets/fonts/IRANSansMobile_UltraLight.ttf
          weight: 700
    - family: BFarnaz
      fonts:
        - asset: assets/fonts/B_Farnaz.ttf
          weight: 700
