name: tapsalon
description: A new Flutter project.

version: 4.0.17+24
environment:
  sdk: ">=2.1.0 <3.0.0"
module:
  androidX: true


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  #  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  intl: ^0.16.1
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  #  percent_indicator: ^2.1.5
  smooth_star_rating: ^1.1.1
  flutter_spinkit: ^4.1.2+1
  flutter_widget_from_html_core: ^0.4.1
  share: ^0.6.4+3
  image_picker: ^0.6.7+2
  url_launcher: ^5.4.11
  #  flutter_calendar_carousel: ^1.4.12
  shamsi_date: ^0.8.1
  carousel_slider: ^2.1.0
  #  google_map_location_picker: ^3.3.2
  #  floating_action_bubble: ^1.1.1
  photo_view: ^0.9.2
  fluttertoast: ^6.0.1
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.5

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tapsalon_icon_200.png"
flutter:


  uses-material-design: true

  assets:
    - assets/images/tapsalon_icon_200.png
    - assets/images/login_bg.png
    - assets/images/circle.gif
    - assets/images/circle2.gif
    - assets/images/instagram.png
    - assets/images/telegram.png
    - assets/images/login_header_pic.png
    - assets/images/main_page_ent_ic.png
    - assets/images/main_page_gym_ic.png
    - assets/images/main_page_salon_ic.png
    - assets/images/user_Icon.png
    - assets/images/marker_ic_1_v1.png
    - assets/images/marker_ic_2_v1.png
    - assets/images/marker_ic_3_v1.png
    - assets/images/place_placeholder.jpeg

  fonts:

    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobile_Bold.ttf
        - asset: assets/fonts/IRANSansMobile_Light.ttf
        - asset: assets/fonts/IRANSansMobile_UltraLight.ttf
          weight: 700
    - family: BFarnaz
      fonts:
        - asset: assets/fonts/B_Farnaz.ttf
          weight: 700
